version: '3'
services:
  mongo-test:
    image: 'mongo'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - 'mongo-test'
    ports:
      - '8000:8000'
    working_dir: /usr/euphoriwiki
    volumes:
      - .:/usr/euphoriwiki:cached
      - /usr/euphoriwiki/node_modules
    env_file:
      - ./.env
    environment:
      - MONGODB_URI=mongodb://mongo-test:27017/wiki_test
      - PORT=8000
      - WAIT_HOSTS=mongo:27017
